checkly/docs.checklyhq.com

site/layouts/partials/footer.html
move `why-checkly` menu from company to product category
=> update why-checkly menu in the footer

gulpfile.babel.js, package-lock.json, package.json, site/layouts/partials/footer.html, src/js/index.js, src/scss/_common.scss, src/scss/_footer.scss
It was a purge issue. As `dot--` classes were loaded dynamically, purgeCSS was removing them on build time.
- Added `dot--` to safe list
- Move styles to footer scss
- Lint gulp tasks
=> fix: safelist status badge classes and lint gulp tasks

site/content/guides/api-monitoring.md, site/content/guides/end-to-end-monitoring.md, site/content/guides/monitoring-as-code.md, site/content/guides/openapi-swagger.md, site/layouts/shortcodes/newtabref.html
@hlenke here is the PR mentioned in https://github.com/checkly/checklyhq.com/pull/6
Now all external links within Guides open in a new tab.
=> refactor: external links open in new tab

site/layouts/pricing/list.html
- merges triggers
- removes Opsgenie and Pagerduty. Adds it to just alerting channels.
- updates pricing example
=> feat: updates pricing page: features + calc

site/layouts/partials/head.html, vercel.json
So this was a little trick I found in the [plausible](https://plausible.io/docs/proxy/guides/nextjs) / vercel docs. It is kindddd of morally dubious, as we're actively going around users who use ad-blocking systems. But i don't find it that bad and plausible noted between 6%-29% of users have adblocking enabled (we're probably on the higher side with tech-savvy users).
So its up to you guys if we should merge this or not. If we do, the client will request `/a/b.js` on our own domain and vercel will do the work of serving `https://plausible.io/js/plausible.js` in its place.
**EDIT**: I implemented this with my instance of plausible on my homepage if you want to see what it looks like in the real world: https://ndo.dev/
**EDIT 2**: The `routes` key is apparently considered legacy and not …
=> feat: rewrite plausible script [ch-00]

site/layouts/partials/head.html, src/js/index.js, vercel.json
In addition to the endpoint for the `plausible.js` snippet, we need to proxy the `/api/event` path because the snippet now attempts to write events to `checklyhq.com/api/event` instead of `plausible.io/api/event` - this of course also allows for gathering more accurate event data because the original endpoint (`plausible.io/api/event`) was also blocked by default through uBlock Origin.
---
Also, squeezed in a little console.log() css update to the hiring raccoon. The ascii raccoon was a bit distorted at the original font-size and I figured it couldn't hurt to match the brand colors while we're at it :) 
Before:
After:
=> feat: proxy plausible events endpoint as well

site/content/docs/groups/_index.md
"Check are scheduled" -> "Checks are scheduled"
=> Groups docs: typo fix

site/content/docs/CICD/github.md
The page said "Check settings", but should say "Change settings"
=> docs: fixed small typo on github deployments page

site/content/learn/headless/basics-taking-screenshots.md, site/content/learn/headless/e2e-account-settings.md, site/content/learn/headless/e2e-file-download.md, site/content/learn/headless/generating-pdfs.md, site/content/learn/headless/managing-cookies.md, site/content/learn/headless/multitab-flows.md, site/content/learn/headless/request-interception.md, src/scss/_syntax.scss
Resolves #167 
Changed highlighting syntax that wasn't working for [new one](https://gohugo.io/content-management/syntax-highlighting/), the old one was highlighting wrong lines of code or empty ones. You can check the sections where the changes were made and the previous/current highlighted lines with more detail bellow. @ragog could you please review them to see if the new ones are okay? thanks in advance! 
- 18-21 to 19-22 to remove empty line
- 24-27 to 25-28 to remove empty line
- 22-27 to 23-28 to remove empty line
- 29-34 to 29-35 added one more line at the end to include downloadUrl const usage Playwright 2
- Changed to 23-26 to remove empty line and add one more at the end to include closing parenthesis
- 10-11,21-31 to 11-12,21-31 to remove empty line and added one more to …
=> Changed highlighting syntax in learn code examples

vercel.json
Remove the `x-frame-options: deny` header in order to allow our site to be embeded in frames. At the request of the jamstack conf people who want to embed our site somewhere.
We can add this back after the conference.
=> fix: remove x-frame-options header

site/content/docs/accounts-and-users/creating-api-key.md
Add info about Account ID to Creating an API key section:
=> chore: add info about account ID [4933]

site/content/docs/runtimes/specs.md
Split the "built-in node modules docs" to a 12.x (from 2020.01) and a 14.x (2021.06 + 2021.10) link.
The runtime details toward the bottom of the page get autogenerated on build from the json served by the backend from `https://api.checklyhq.com/v1/runtimes`.
=> feat: update docs for 2021.10

site/layouts/docs/_markup/render-heading.html, src/scss/_docs.scss
=> feat: now headers in the docs are direct links for handy copy & paste

site/content/docs/accounts-and-users/_index.md, site/content/docs/accounts-and-users/adding-team-members.md, site/content/docs/accounts-and-users/creating-api-key.md
Currently the url for the team section (now "Account & Users") is dead link. This provides an alias to redirect to the "account and users" section.
=> fix: add alias for team url [5412]

site/content/docs/accounts-and-users/creating-api-key.md
Changing `account-based` to `account-scoped` to use the same terminology in the doc than in the web-app.
Deprecation warning in the web app:
=> fix: changed based to scoped for consistency [5336]

site/layouts/partials/all-features.html, site/layouts/partials/api-monitoring-section.html
API Monitoring: `s/responds/respond`
All features at a glance: `s/using/use`
=> fix: typos in 'API Monitoring' and 'All features at a glance' sections

site/layouts/partials/jobs-embeded.html
Tiny change: Deleting hardcoded timezones on the careers page.
=> deleting hardcoded timezones

vercel.json
Rewrite requests to `docs.checklyhq.com` to `checklyhq.com/docs`
Following: https://vercel.com/support/articles/can-i-redirect-from-a-subdomain-to-a-subpath
Umut has already added a CNAME to point `docs.checklyhq.com` to `www.checklyhq.com` and thereby take us to the marketing page. From there, the `vercel.json` redirects added in this PR should take us the rest of the way :+1:
=> feat: add redirect from docs.checklyhq.com -> checklyhq.com/docs [sc-00]

site/content/docs/monitoring/monitoring.md
We recently introduced changes in how setup scripts are run during retries. Before, setup scripts would not be re-executed if a check was retried. Now, setup scripts are re-executed during the retry.
=> docs: describe new setup script retry behaviour [sc-6902]

site/content/docs/alerting/webhooks.md
We recently added the `GROUP_NAME` variable for WebHook alerts. If the check is assigned to a group, the `GROUP_NAME` variable contains the name of that group. If the check isn't assigned to any group, `GROUP_NAME` is undefined.
=> feat: document GROUP_NAME webhook var [sc-6126]

site/content/docs/integrations/prometheus.md
Linking directly to the web UI should make the setup process easier. I added `target="_blank"` so that the page opens in a new tab.
=> Add link to integrations settings in webapp

.github/pull_request_template.md, site/content/product/terraform-provider.mmark
Fixed a broken link on the terraform landing page.
=> fix: Fix link to terraform docs

site/layouts/shortcodes/runtimes.html
Updating the runtime docs to display a deprecation warning and expiration date.
Deprecated runtime:
Stable runtime:
> Resolves #[issue-number]
=> chore: update runtime docs with deprecation warning [sc-9735]

site/content/docs/snippets/_index.md, site/content/docs/snippets/handlebars-snippets.md
The "On This Page" section of the snippets page (https://www.checklyhq.com/docs/snippets/) is blank. This is because the page is using h3 instead of h2 for the headers. This PR just updates the headers, which resolves the issue.
=> fix: use h2 for snippets headers

__checks__/404.check.js, __checks__/pricing.check.js, package-lock.json, package.json
The local tests had a too new expect version and weren't compatible with the Checkly runtime.
=> fix: adjust expect version to match checkly runtime

site/content/integrations/_index.md
Had a reminder popping up to remove this `new` label here. :)
=> feat: remove "new" label from pulumi provider

site/content/docs/api-checks/setup-teardown-scripts.md, site/content/docs/browser-checks/variables.md
This was not in our docs yet but was live in the editor and backend.
=> docs: adds docs on generic runtime variables

site/content/docs/integrations/prometheus.md
Add new `disableTagParsing` flag to the Prometheus documentation.
> Resolves #[issue-number]
- Webapp PR https://github.com/checkly/checkly-webapp/pull/3158
- Backend PR https://github.com/checkly/checkly-backend/pull/3425
=> docs: add disableTagParsing flag in prometheus docs [sc-10935]

site/content/security/security-response.md, site/data/security/faq.yml
Added SOC2 information on `/security`:
And `/security/security-response/`:
=> feat: add SOC2 information

site/content/learn/headless/iframes.md, site/content/samples/playwright/iframe-access.js, site/content/samples/puppeteer/iframe-access.js
Add quick iframe sections to `/learn`.
=> docs: add simple iframe snippets

site/content/docs/private-locations/checkly-agent-guide.md
It's come up that users need the Checkly agent to trust internal TLS certificates. This PR adds documentation explaining the necessary steps for this.
Another approach is to just set `NODE_TLS_REJECT_UNAUTHORIZED=0` - disabling all TLS certificate validation. This is insecure, but it's simpler since you don't need the certificate to get things working. We could consider mentioning this approach for debugging purposes, but I'm not sure if it's worth it.
=> docs: explain how to trust TLS certs in agent

site/layouts/partials/head.html
The intercom script was only loaded on scroll. This results in a significant delay of having the intercom banner visible.
Changing the eventListener to `DOMContentLoaded` reduces our lighthouse score slightly but not too much.
https://user-images.githubusercontent.com/54396648/196427676-796aa2d9-a3d0-4317-8635-2f7c6b4b97cf.mp4
- using `scroll`
- using `DOMContentLoaded`
- using `scroll`
- using `DOMContentLoaded`
> Resolves #[issue-number]
=> refactor: load intercom script on page load [sc-12058]

site/content/guides/puppeteer-to-playwright.md
This fixes a one letter typo in our guide for migrating from Puppeteer to Playwright.
=> docs: typo

site/content/docs/integrations/pagerduty.md
Add it to the docs that we only support the US instance of pagerduty at the moment
=> docs: add to the documentation that we only support US instance [sc-0]

package-lock.json, site/content/docs/browser-checks/variables.md
We recently removed access to locked environment variables for read-only users. We can add this to the docs now.
[The updated page is here.](https://checklyhq-6ghpzn1x2-checkly.vercel.app//docs/browser-checks/variables/)
=> docs: document read-only locked env var behaviour [sc-10987]

site/content/docs/alerting/webhooks.md
Related to https://app.intercom.com/a/apps/ep3ft8gg/inbox/inbox/4015446
=> docs: add triple brackets callout on webhooks page

site/layouts/partials/navbar.html
- Instead of hardcoded appending of UTM tags to 3 links to our webapps `/signup` page in the nav and hero section, we will change it to dynamically fetch all nodes with `a[href*="app.checklyhq.com"]'` and append them to all of the results.
=> fix: dynamically append utm tags to all links to the webapps /signup page [sc-12942]

src/scss/_pricing-v2.scss
- Fix `:focus` styling on these pricing card cta btns. See screenshots below.
Before:
After:
=> fix: focus styling on pricing cards cta btns [sc-00]

site/layouts/partials/scripts.html
- Sets the `utm_originalsource` even on the first visit
- Sets `utm_originalmedium` as well for more detailed attribution
=> fix: always set utm_originalsource and utm_originalmedium

site/layouts/pricing/list.html
I also updated two typos where currency wasn't formatted properly. The enterprise price of $1,500 was formatted as $1500 and browser check runs were shown as 5000 without the thousand separator.
=> Add Incidents and Custom dashboard CSS to pricing

site/config.toml, site/layouts/partials/hero-section.html
Add link to MaC site on the homepage
=> feat: add link to MaC on homepage [sc-14224]

site/content/product/monitoring-as-code.mmark
Add new blog post on MaC screen
=> docs: add MaC blog post to marketing site [sc-14234]

site/content/docs/cli/installation.md
mini update to show Node.js 16 prereq
=> docs: mentions prereq in extended installation docs

.github/workflows/checkly.yml
We currently deploy checks for MaC with each PR ([f.ex, here](https://github.com/checkly/checklyhq.com/actions/runs/4477517155/jobs/7869139769)). Since PR's aren't yet reviewed and approved, though, we shouldn't be deploying the checks.
With this PR, the checks will only be deployed when there's a production Vercel. This will make sure that the deployed checks are always using `main` rather than code from PR branches.
=> chore: only update checks on production deployments

site/content/docs/dashboards/_index.md, site/content/docs/dashboards/dashboard-customization.md, site/content/docs/dashboards/dashboard-url.md, site/content/docs/dashboards/incidents.md, site/content/docs/terraform-provider/dashboards.md, site/content/product/dashboards.mmark, site/data/pricing/faq.yml, site/layouts/partials/all-features.html, site/layouts/pricing/list.html
Since dashboards will get the `private` option soon, I'm removing mentions of "public" in the docs and marketing site.
=> feat: remove 'public' mentions for dashboards feature [sc-15375]

site/content/docs/cli/installation.md
- adds section to CLI installation docs to directly download a CLI distribution
=> docs: adds direct downloads section [sc-00]

__checks__/site.check-group.ts
Update logical id for checks not to be overwritten by [marketing website checks](https://github.com/checkly/checkly-marketing-website/blob/main/__checks__/site.check-group.ts).
=> fix: change logical id of docs checks to not be overwritten by marketing site [sc-00]

site/content/docs/cli/constructs-reference.md
- Slack uses the `URL` object for it's URL type, not a `string`
=> fix: adds URL() to Slack example

site/content/docs/cli/command-line-reference.md
Docs show example of using tags with CLI to trigger tests with (production AND webapp) OR (staging AND backend) tags, but the code example used included `production` rather than `staging`, minor typo fix 🙂
=> docs: Fixing incorrect `tag` param staging vs production

site/content/docs/cli/command-line-reference.md
As discussed in slack. :) A tiny wording change for the new CLI flag.
=> fix: adjust wording of `--no-schedule-on-deploy` flag

vercel.json
Let's try this again. 🫣 The `trailingSlash` option worked fine in the preview environment but seems to puzzled our the tunneling setup. 
I disabled it for now, because the base repo (checkly/checkly-marketing-site) has it defined. Let's see what happens now.
Generally, **we decided that all links / urls should include `www` and a trailing `/`** to avoid Googlebot redirects.
=> fix: remove trailing slash option

site/content/guides/api-monitoring.md, site/content/guides/monitoring-as-code.md, site/content/guides/setup-scripts.md, site/content/learn/_index.md
Weekly clean up of Search Console Errors. It's mainly adding trailing slashes to avoid us linking to redirects and aligning the sitemap with the actual content (exclude `/learn/` from sitemap).
=> fix: update some links to avoid redirects

site/content/docs/browser-checks/_index.md, site/content/docs/private-locations/_index.md, site/content/docs/private-locations/checkly-agent-configuration.md
The agent is being updated to support ARM64 and Apple silicon. This PR updates the docs accordingly.
=> feat: update docs to reflect Private Location arm64 support

site/content/docs/browser-checks/login-scenarios.md
This is probably a rather common problem, and  the excellent blog post by @stefanjudis provides a good solution. However it is not so easy to find. The `Login Scenarios` doc feels like a natural place for a user to look for a solution (I started there) and addition would also make it findable by people who search the docs for '2FA'.
=> docs: add 2fa login blog post to resource list

README.md, site/content/docs/heartbeat-checks/_index.md
Clarify why we're blocking certain user agents from being able to ping the heartbeat ping endpoint and list the blocked user agents.
=> doc(heartbeat): list blocked ping user-agents [sc-17558]

site/content/docs/private-locations/checkly-agent-configuration.md
Previously we were recommending an auto-update tool for the Agent. A limitation of this auto-update setup is how it handles breaking changes. If we ever release an Agent with breaking changes (or a regression), it will triggering alerts for users at a time when they don't expect it. To avoid this, users should just explicitly trigger an update of the Agent. This will make sure that if there's an alert, it happens during work hours and they know immediately that it's caused by the Agent upgrade.
This recently became a problem when deprecating old runtimes. We already recommended to existing users to not use auto-upgrade setups.
=> docs: remove Agent auto-update recommendation

site/content/docs/terraform-provider/_index.md, site/content/docs/terraform-provider/alerting.md, site/content/docs/terraform-provider/checks-groups.md, site/content/docs/terraform-provider/command-line-triggers.md, site/content/docs/terraform-provider/maintenance-windows.md
Just updated the links to the TF registry. Seems like the URLs changed with the latest provider release.
=> boyscout: update registry links

site/content/docs/integrations/prometheus-v2.md
…onds
We recently introduced a new metric `checkly_time_to_ssl_expiry_seconds` for monitoring SSL expiry. This PR adds some basic documentation for it.
=> docs: add documentation for Prometheus V2 SSL Expiry metric

site/content/docs/cli/using-constructs.md
We currently don't document that project `logicalId`'s should be unique within a Checkly account. Not having this uniqueness can cause `checkly deploy` of one project to overwrite the checks of another project.
This was brought up in the [community slack](https://checklycommunity.slack.com/archives/C04349E26EN/p1695950799351559)
=> docs: clarify that project logicalIds should be unique

site/content/docs/private-locations/running-on-kubernetes.md
There's a little typo in the docs. The directory name should be [helm-chart](https://github.com/checkly/checkly-k8s/tree/main/helm-chart).
=> docs: fix typo

site/content/docs/monitoring/allowlisting.md, site/content/docs/monitoring/ip-info.md, site/content/guides/end-to-end-monitoring.md
* [ X ] Docs
Feedback from https://app.intercom.com/a/inbox/ep3ft8gg/inbox/conversation/135570604715690
=> replace 'whitelist' with 'allowlist'

site/content/docs/cli/constructs-reference.md, site/content/docs/heartbeat-checks/_index.md, site/content/docs/integrations/prometheus-v2.md
=> fix: 404 redirection on docs [sc-00]

site/content/docs/CICD/vercel-deployment-protection.md, site/content/docs/CICD/vercel.md, site/content/docs/api-checks/setup-script-examples.md, site/content/docs/browser-checks/login-scenarios.md
- adds more comprehensive docs on how to work around Vercel deployment protection
- adds links / callouts to that section on a couple of relevant pages.
=> docs: adds vercel deployment protection docs

site/content/guides/api-monitoring.md, site/content/guides/end-to-end-monitoring.md, site/content/guides/monitoring-as-code-cli.md, site/content/guides/monitoring-as-code.md, site/content/guides/openapi-swagger.md, site/content/guides/puppeteer-to-playwright.md, site/content/guides/setup-scripts.md, site/content/guides/the-programmable-monitoring-platform.md, src/scss/_guides.scss
Add Read More on /guides as we have on /docs + /learn. This implementation was approved by the SEO agency.
=> feat: add Read More section on /guides [sc-18864]

site/content/docs/cli/constructs-reference.md
The CLI now supports `RetryStrategyBuilder.noRetries()` to disable the default retry strategy (introduced in CLI 4.6.3 with https://github.com/checkly/checkly-cli/pull/944). 
I'm not sure there's a better way to rephrase the following sentence, since `noRetries()` doesn't take an `options` argument:
> For all of the methods above, the `options` argument can be used to customize the following properties:
=> docs: document RetryStrategyBuilder.noRetries()

site/config.toml
Avoid unnecessary redirects by using trailing slash on links
=> fix: add slash on side menu items [sc-00]

site/layouts/partials/head.html, site/layouts/welcome/list.html
Some of our pages with a good amount of traffic on the learn section are missing one or more of the required Open Graph tags. Fix og:title and add og:url
=> fix: add missing open graphs [sc-20405]

site/content/docs/testing/_index.md, site/content/guides/monitoring-as-code.md, site/content/guides/the-programmable-monitoring-platform.md
=> Seo updates 2

site/content/docs/cli/command-line-reference.md, site/content/docs/cli/constructs-reference.md
We recently released support for CLI retries in [CLI version 4.8.0](https://github.com/checkly/checkly-cli/releases/tag/4.8.0). This PR adds documentation for the new feature.
In particular, this PR changes the [Command Line Reference page](https://checklyhq-com-git-chrislample-document-cli-retri-e45ad8-checkly.vercel.app/docs/cli/command-line-reference/) and [Constructs Reference page](https://checklyhq-com-git-chrislample-document-cli-retri-e45ad8-checkly.vercel.app/docs/cli/constructs-reference/).
=> docs: document CLI retries support

site/content/_shared/otel-api-and-endpoint.md, site/content/docs/traces-open-telemetry/instrumenting-code/ruby-on-rails.md
fixes the ruby on rails redirect https://www.checklyhq.com/docs/open-telemetry/instrumenting-code/ruby-on-rails/
correct shared steps to remove enabling the HTTP headers propagation
Should redirect https://checklyhq-com-git-mda-update-traces-checkly.vercel.app/docs/open-telemetry/instrumenting-code/ruby-on-rails/ properly :) 
and updates from 
to
=> Fix RoR redirect & correct shared steps

site/content/docs/traces-open-telemetry/_index.md, site/layouts/partials/docs-title.html
* [ X ] Docs
* [ X ] Code is linted (`npm run lint`)
The title of the documentation page is now separated from the title that appears on the sidebar menu. Each documentation page now has a param called `navTitle` that dictates the title of the sidebar menu.
You can see that the title on the sidebarnav of this page is different than the page H1.
=> Added param for navTitle to be used in the menu of the docs

site/layouts/partials/head.html
* [ X ] Learn
This first commit tries to fix the elongated Meta TItle Tags in our Hugo template
=> Reducing Title Tag size in template

site/content/docs/monitoring/allowlisting.md
Adding information around Checkly traffic being autofiltered when using Google Analytics 4
* [] Content & Marketing
=> docs: mention ga4 autofiltering

site/content/guides/end-to-end-monitoring.md, site/content/guides/monitoring-an-openapi-spec.md, site/content/guides/monitoring-ecommerce-apps-using-playwright.md, site/content/guides/monitoring-ecommerce-apps-using-terraform.md, site/content/guides/monitoring-the-stripe-api.md, site/content/guides/moving-from-puppeteer-to-playwright.md, site/content/guides/setup-scripts-for-apis.md, site/content/guides/the-programmable-monitoring-platform.md, site/layouts/guides/list.html, site/layouts/guides/single.html, vercel.json
* [ X ] Guides
Optimized the Titles, Meta Titles, and URL structure for all of the guides
=> Optimized SEO for Guides

__checks__/docs.spec.ts, site/content/docs/_index.md, site/content/guides/monitoring-as-code.md, site/layouts/partials/head.html, vercel.json
* [ X ] Learn
* [ X ] Guides
I added a new MaC guide, fixed the redirect for it, and simplified the Meta Title logic
=> fixed MaC guide, removed old redirect, fixed the Meta Titles

site/content/docs/integrations/prometheus-v2.md
now allows for 50 requests per minute, a minimum scrape interval of 2 seconds.
=> increase api limit in prometheus endpoint

site/content/learn/playwright/_index.md, site/content/learn/playwright/what-is-playwright.md, site/layouts/learn/list.html, site/layouts/learn/single.html, site/layouts/partials/learn-breadcrumb.html, site/layouts/partials/learn-menu.html, src/scss/_learn.scss
- ports over best nav fixes and best practices from docs section.
- cleans up the list page
=> feat: apply changes / fixes from docs to learn [sc-00]

site/content/learn/playwright/challenging-flows.md, site/content/learn/playwright/checkout-testing-guide.md, site/content/learn/playwright/emulating-mobile-devices.md, site/content/learn/playwright/file-download.md, site/content/learn/playwright/generating-pdfs.md, site/content/learn/playwright/google-login-automation.md, site/content/learn/playwright/how-to-search.md, site/content/learn/playwright/how-to-set-up-locally.md, site/content/learn/playwright/iframe-interaction.md, site/content/learn/playwright/intercept-requests.md, site/content/learn/playwright/login-automation.md, site/content/learn/playwright/managing-cookies.md, site/content/learn/playwright/microsoft-login-automation.md, site/content/learn/playwright/multitab-flows.md, site/content/learn/playwright/navigation.md, site/content/learn/playwright/performance.md, site/content/learn/playwright/playwright-vs-cypress.md, site/content/learn/playwright/playwright-vs-selenium.md, site/content/learn/playwright/scraping-behind-login.md, site/content/learn/playwright/taking-screenshots.md, site/content/learn/playwright/testing-account-settings.md, site/content/learn/playwright/testing-coupons.md, site/content/learn/playwright/user-signup-automation.md, site/content/learn/playwright/web-scraping.md, site/layouts/shortcodes/readfile.html, src/scss/_learn.scss
- removes the unneeded, left over Playwright tabs / tab scructure
- updates the `readFile` and related "run in Checkly" code to reflect new situation.
no more tabs + correctly aligned "run in checkly button"
desktop: 
mobile:
=> refactor: removes unneeded playwright tabs [sc-00]

site/content/docs/traces-open-telemetry/importing-traces/troubleshooting-missing-spans.md, site/layouts/_default/sitemap.xml
Our sitemap has some /tags pages autogenerated by Hugo and thats not good for SEO. This change was requested by Growtika https://trello.com/c/EhuEAL6H/207-november-404-tag-pages-in-sitemap
=> fix: remove /tags from sitemap [sc-00]

site/content/docs/traces-open-telemetry/instrumenting-code/nextjs.md
We were missing a closing } so it didn't work when copy-pasting
=> add missing }, thanks Mark!

site/content/learn/playwright/testing-in-parallel.md
=> Fix header formatting on test in parallel page

site/content/docs/cli/constructs-reference.md, site/content/docs/groups/_index.md
=> Add clarification around how group and check configurations interact

vercel.json
Only the root was redirected, not nested pages.
=> fix: redirect all docs. traffic to /docs

vercel.json
=> fix: redirect try 3. with trailing slashes

site/config.toml, src/scss/_guides.scss, src/scss/_learn.scss
hides h3 links in TOC for /learn and /guides
=> feat: set toc level to h2 for learn and guides

site/layouts/docs/list.html, site/layouts/docs/single.html, site/layouts/guides/single.html, site/layouts/learn/single.html, site/layouts/partials/head.html, site/layouts/partials/structured-data-article.html
* [z] Other
Adds a structured data element to all relevant article pages in docs, guides and learn. It juggles with some fallbacks here and there to get most relevant data in. Read about structured data here: https://developers.google.com/search/docs/appearance/structured-data/article
Example of injected data:
```html
<script type="application/ld+json">
{
"@context": "https://schema.org",
"@type": "Article",
"headline": "Dealing with waits and timeouts in Playwright",
"description": "When you’re trying to test your site’s core user flows with Playwright and are facing an element not being loaded, many take the shortcut of waiting for a fixed amount of time by adding a hard-coded timeout. Hard timeouts are an anti-pattern, as they lower performance, increase the chances of a script …
```
=> feat: adds structured data script for SEO

.github/auto_assign.yml, .github/dependabot.yml
- don't assign tnolet as default reviewer
- let dependabot alert on `hugo` versions
=> chore: remove tnolet as default. alert on hugo versions.

site/content/docs/api-checks/setup-script-examples.md
Super tiny change. `import { axios } from 'axios'` doesn't work, so I changed it to the working `import axios from 'axios'`.
Axios uses the default import in their documentation (for example, [in this code snippet](https://www.npmjs.com/package/axios/v/0.27.2#form-data)).
I also verified this by creating two checks. They're identical except for the axios import statement in the setup script.
* You can view them in my account (`1631b1ea-30aa-432f-bb37-cf96f43a1480`)
* I'm on the latest runtime 2024.09
* [axios as named import](https://app.checklyhq.com/checks/094a4014-d448-4809-9ac8-f59204f8d5f4) (failing with `There was an error in your setup script: TypeError: Cannot read properties of undefined (reading 'get')`)
* [axios as default …
=> fix: axios import statement in API setup script example

site/content/docs/alerting-and-retries/sms-delivery.md
The issue has been resolved and we can re-enable SMS for Saudi Arabia again [[see Slack]](https://checklyhq.slack.com/archives/CSG0W8UTG/p1742546840793639?thread_ts=1740650822.776519&cid=CSG0W8UTG
)
Reverts checkly/docs.checklyhq.com#1233
=> Revert "feat: remove saudia arabia from allowed countries for SMS [sc-00]"

site/content/guides/monitoring-as-code.md, site/content/learn/incidents/modern-root-cause-analysis.md, site/content/learn/monitoring/transaction-monitoring.md, site/content/learn/playwright/_index.md
=> new links per Growtika

site/content/docs/playwright-checks/_index.md, site/content/docs/playwright-checks/add-to-group.md, site/content/docs/playwright-checks/reference.md
Fix jiti vs ts-node in onboarding description
=> Add new logicalId

site/content/docs/playwright-checks/custom-dependencies.md, site/content/docs/private-locations/_index.md
After request from @MariadeAnton, I took an existing draft and turned it into a docs page.
Draft: https://www.notion.so/checkly/Public-page-Private-Locations-and-Custom-dependencies-in-Playwright-Check-Suites-200ec050b06e80ab81cacdc0ec8d23ec
=> Add new PWN docs section for custom dependencies

site/content/docs/heartbeat-monitors/_index.md, site/content/docs/heartbeat-monitors/ping-examples.md
* Updated references to Heartbeats from 'Heartbeat check' to 'Heartbeat monitor'
* Removed callout saying that Heartbeats are only for Team and Ent
* Fix Heartbeat sidebar issue
=> Update Heartbeat pages based on recent name and pricing changes

site/content/docs/cli/command-line-reference.md
--debug-bundle is for internal use and was never intended to be used by customers without supervision.
=> Remove debug bundle

site/content/docs/cli/constructs-reference.md
- Explicitly refer to `global` prop in alert settings. [Slack thread](https://checklyhq.slack.com/archives/C04PFSV5W3B/p1758009814134669)
=> docs: clarify alertEscalationPolicy settings in constructs reference
