site/layouts/learn/single.html, src/scss/_learn.scss
=> Add breadcrumb to Headless Guides

site/layouts/partials/footer.html, src/js/index.js, src/scss/_common.scss
Adds the correct link to the new status page + a nice indicator
=> feat: adds correct status link + indicator [ch-000]

site/data/pricing/faq.yml, site/layouts/pricing/list.html
=> Pricing Page Update

site/content/jobs/support-engineer.md, site/content/product/api-monitoring.mmark, site/content/product/synthetic-monitoring.mmark
Update intervals and removed support engineer job
=> Update Product Pages Intervals

site/content/docs/api-checks/assertions.md
* https://app.intercom.com/a/apps/ep3ft8gg/inbox/inbox/conversation/135570600038137
=> Clarify docs on JSON path assertions

.github/dependabot.yml
=> chore: set PR limit to 2 for dependabot

src/js/index.js
=> chore: add hiring console.log()

gulpfile.babel.js, site/layouts/partials/scripts.html, src/js/xml2json.js
=> move xml2json from remote to local

package-lock.json, src/scss/_case-studies.scss
=> Update minimal layout issues

site/content/learn/headless/_index.md
Spotted while going over the website.
=> Minor typo fix

site/layouts/guides/list.html, site/layouts/partials/footer.html, src/scss/_docs.scss, src/scss/_footer.scss, src/scss/_guides.scss
=> fix: samll fixes website

site/content/careers/_index.md
=> change employee number

site/data/pricing/faq.yml, site/layouts/partials/alternativeto/alternativeto-hero-section.html, site/layouts/pricing/list.html, src/scss/_pricing-v2.scss
Removes any mention of "trial" on our website.
=> Tnolet remove trial sc0000

site/content/docs/api-checks/setup-teardown-scripts.md
Spotted a broken img while using our docs.
=> fix: broken img url

site/layouts/_default/baseof.html, site/layouts/docs/baseof.html, site/layouts/learn/baseof.html, site/layouts/product/baseof.html, site/layouts/why-checkly/baseof.html
Move `promo-banner` markup inside `<body>`.
=> fix: move banner inside body [sc-00]

site/content/docs/integrations/terraform.md
Update TF and show how to use user keys and account id
=> docs: update TF docs with user keys

site/layouts/pricing/list.html
Edit some copy in the contact sales form and correct the form reset after submit.
=> edit contact sales form

site/content/docs/terraform-provider/parameterized-resources.md
Typo, extra closing curly brace in wrong place
=> Update parameterized-resources.md / typo

site/content/docs/browser-checks/browser-checks.md
Quick docs improvement mainly to familiarize myself with the docs and marketing site. :)
=> docs: add awesome-playwright

site/content/guides/api-monitoring.md, site/content/guides/monitoring-as-code.md, site/content/guides/openapi-swagger.md
Was just reading the `/guides` section and did some minor tweaks here and there. There's nothing spectacular in this PR. 🙈
=> docs: add minor tweaks to guides section

site/content/docs/integrations/prometheus.md
I recently added new private location metrics to Prometheus. This PR adds them to our documentation as well. It might make sense to add more thorough documentation in the private location section of the docs, but for now this PR adds some basic info to the Prometheus section.
=> Document new private location Prometheus metrics

site/content/docs/private-locations/proxy.md
Fixed syntax in code examples.
=> fix: async IIFE syntax [sc-00]

_checkly/404.check.js, _checkly/home.check.js, _checkly/pricing.check.js, _checkly/product-api.check.js, _checkly/product-synthetic.check.js
adds a `_checkly` directory with check code to link to our browser checks in the Production E2E account
=> adds checks as code (sc-9201)

site/content/docs/browser-checks/partials-code-snippets.md
Started fixing a typo and rewrote some sentences to make them shorter.
=> docs: tiny fixes for require syntax docs

site/layouts/partials/head.html
Add GTM and LI tracking for Marketing initiatives.
=> Add pixels

site/content/docs/private-locations/_index.md, site/content/docs/private-locations/checkly-agent-guide.md
=> docs: adds "known limitations" section

site/content/learn/headless/test-data-intro.md
Added Faker mention to the [Handling Test Data](Handling test data) page.
=> docs: add faker snippet

.husky/_/husky.sh, site/content/docs/integrations/prometheus.md
Add info section to explain how to use Prometheus labels with checks/group tags
=> docs: add info about prometheus tag labels

site/layouts/partials/head.html
=> feat: add GA/GTM tag

site/content/docs/snippets/_index.md
Just added syntax highlighting to some snippets in the docs.
=> docs: add syntax highlighting

site/content/docs/snippets/_index.md
After talking to @clample we agreed to make the docs clearer for snippets that require other snippets.
=> docs: adjust snippet docs

site/content/docs/CICD/vercel.md
A snippet was missing a semi colon.
=> Fix code snippet

__checks__/README.md, site/content/docs/browser-checks/github-code-sync-api.md, site/content/docs/browser-checks/github-code-sync.md
=> docs: updates target

site/layouts/pricing/list.html
Update `Aggregated data retention` for free plan
=> chore: update aggregated data retention free plan

site/content/docs/browser-checks/github-code-sync.md
=> docs: update GH sync docs

site/content/privacy/_index.md
Adding Hotjar to Privacy Policy page as mentioned on [Slack](https://checklyhq.slack.com/archives/C01JADUE2EP/p1660139318119479).
=> feat: add hotjar to privacy policy

site/layouts/partials/head.html, site/layouts/partials/scripts.html
=> feat: update GTM snippet

site/content/docs/browser-checks/login-scenarios.md
=> Fix broken links to more login resources

site/content/learn/headless/e2e-google-login.md
=> Update typo in google e2e doc

site/data/security/faq.yml
Updated security FAQs to move SOC2 up and remove redundant question.
=> feat: adjust security FAQs

site/content/docs/CICD/vercel.md
=> docs: changed wrong link from CICD Vercel

site/content/docs/private-locations/checkly-agent-guide.md
=> docs: adds note on resolving local addresses from Docker Desktop

site/content/launch-week/_index.md, src/scss/_launch-week.scss
=> feat: adjust launch-week copy

site/content/launch-week/_index.md, site/layouts/launch-week/list.html
=> feat: add lw video links

site/layouts/launch-week/list.html, src/scss/_launch-week.scss
=> feat: add times to lw page

site/content/launch-week/_index.md
=> feat: update launch week page for day one

site/layouts/partials/footer.html
=> feat: adds Slack link

site/content/launch-week/_index.md
=> feat: add lw-1-2 updates

site/layouts/partials/head.html
=> feat: adds hotjar snippet

site/content/docs/browser-checks/github-code-sync-api.md, site/content/docs/browser-checks/github-code-sync.md, site/content/launch-week/_index.md
=> feat: update lw info

.github/dependabot.yml, package-lock.json, site/content/docs/integrations/_index.md
- Add missing integrations to index page
- Fix dependabot indentation
=> fix: add missing integrations to list [sc-12064]

package-lock.json, package.json
- Removes a few unused dependencies
=> fix: rm unused deps [sc-00]

site/content/docs/private-locations/checkly-agent-guide.md
User pointed out mistake in formula.
=> docs: updates wrong formula in docs

site/content/docs/maintenance-windows/_index.md
> This should be a quick review.
=> Major breaking change (added a missing full stop)

site/layouts/pricing/list.html
small addition to pricing table
=> feat: adds certificates to pricing table

site/layouts/pricing/list.html
- Fixes feature not-included icons
Before:
After:
=> fix: pricing page not-included icons [sc-12671]

.github/pull_request_template.md
- Small update to the PR template:
- Removed the "Resolves .." section by default because its rarely used for changes by an internal person, right?
- Added section for screenshots for visual changes, like in webapp repo
Just suggestions from me - feel free to take or leave any of them :blush:
=> chore: update PR template [sc-00]

site/layouts/careers/list.html, src/scss/_careers.scss
Missed updating one button and Kaylie wanted another one in the bottom.
=> feat: update buttons on career page

site/layouts/pricing/list.html
New bullet point for Team plan
=> chore(pricing): team plan bullet checks included [sc-12899]

site/layouts/partials/scripts.html
- Request from Lazar/marketing: also persist an original `utm_source` as "first touch source".
Requires: https://github.com/checkly/checkly-webapp/pull/4101
=> feat: persist and send along utm_originalsource if set [sc-12961]

site/content/docs/runtimes/specs.md
Only added Node 16 to the runtime specs.
=> feat: add runtime spec docs

site/layouts/pricing/list.html
Fix copy for team plan user limitation
=> fix: team plan user limitation [sc-00]

site/layouts/pricing/list.html, src/scss/_pricing-v2.scss
Update CTA for "Start free trial" on TEAM plan
=> feat: start free trial button [sc-13010]

site/layouts/pricing/list.html, src/scss/_pricing-v2.scss
Minor pricing page copy changes
=> chore: pricing page copy adjustments [sc-13213]

site/layouts/pricing/list.html
Removed duplicate `client certificate` from feature overview.
Before: 
After:
=> refactor(pricing): remove duplicate `client certificate` from feature overview

site/layouts/partials/hero-section.html, site/layouts/partials/scripts.html
- Fix `utmOriginalSource` attribution
- Fix appending multiple utm params to links
=> fix: utm tag appending and originalSource

site/layouts/partials/scripts.html
- Code clean up for the `../partials/scripts.html` UTM persistence javascript
- Rename variables to make the whole thing easier to follow
- Combine some logic
=> chore: cleanup utm param saving [sc-00]

site/layouts/pricing/list.html, src/scss/_pricing-v2.scss
- Moved the card buttons to the middle
- Updated the button colors
- Added disclaimer to Hobb and Team plan
- Updated the cards to have the same height
=> refactor(pricing): update pricing cards [sc-13310]

site/layouts/pricing/list.html, src/scss/_pricing-v2.scss
Reverts checkly/checklyhq.com#614
We want to wait for another PR before merging this one to avoid confusion.
=> Revert "refactor(pricing): update pricing cards [sc-13310]"

site/layouts/pricing/list.html
- Remove `startOnTrial` query param from "Start Trial" link to sign up at webapp.
- Users now always start on `TRIAL` plan (see: https://github.com/checkly/checkly-backend/pull/3804)
=> chore: rm startOnTrial query param [sc-13289]

site/layouts/partials/read-case-stuides.html
=> fix: finn auto url on main page

README.md, __checks__/home.spec.js, site/config.toml, site/layouts/partials/hero-section.html
- Update home page taglines
- Update readme text
- Update meta tags text
=> feat: new tagline [sc-13472]

site/content/customers/_index.md, site/layouts/customers/list.html
Add new card for Solutia case study
=> feat: add Solutia case study [sc-13614]

site/layouts/pricing/list.html
=> chore: reduce hobby api check runs [sc-00]

site/content/product/synthetic-monitoring.mmark
- Uploaded `synthetic-browser-check-how-works.mp4` to S3 and pointed https://www.checklyhq.com/product/synthetic-monitoring/ to it
=> feat: move synthetic-browser-check-how-works.mp4 to S3 [sc-00]

site/content/launch-week/_index.md, site/layouts/launch-week/list.html, src/scss/_launch-week.scss
=> feat: update launch-week page

src/scss/_launch-week.scss
Making the launch week video look good on mobile
=> feat: fix lw video responsiveness

site/content/docs/cli/constructs.md
Added required `locations` property to `CheckGroup` example snippet.
=> docs: update CheckGroup docs

site/content/docs/CICD/vercel.md
=> Fix docs vercel content refinement663]

site/content/docs/browser-checks/variables.md
=> chore: update code example for browser check env vars [sc-13479]

site/content/docs/browser-checks/login-scenarios.md
Just updated the example to use `.getByX` instead of `locator` here as well.
=> chore: update login code example [sc-00]

site/content/docs/browser-checks/timeouts.md
Adding a TS tab. The content has already been reworked by @ragog in #625
=> chore: add ts example to timeouts [sc-13482]

site/content/docs/browser-checks/file-system.md
=> chore: update file system code example to PWT [sc-13477]

site/content/docs/browser-checks/timeouts.md
=> chore: add disclaimer about action timeout [sc-14007]

site/content/docs/terraform-provider/testing-scripts-locally.md
=> feat(docs): rework the testing scripts locally page [sc-13493]

site/content/docs/terraform-provider/_index.md
=> feat(docs): rework getting started tf page [sc-13491]

site/content/launch-week/_index.md
=> Update SOC2 Copy

site/content/docs/monitoring/whitelisting.md
=> feat(docs): update whitelisting example script to PWT [sc-14098]

site/content/product/monitoring-as-code.mmark
Fix typo (CODE ANC COLLABORATE)
=> fix: typo in MaC screen [sc-00]

site/content/docs/cli/constructs.md
=> fix minor typo

site/content/guides/monitoring-as-code-cli.md, site/layouts/shortcodes/rawhtml.html
=> Add launch video to CLI guide

site/content/docs/dashboards-v2/dashboard-customization.md
=> fix: update typo under public dashboard custom domain section [sc-00]

site/content/docs/api-checks/setup-teardown-scripts.md, site/content/docs/browser-checks/variables.md
- add new `REQUEST_URL` and `GROUP_BASE_URL` environment variables docs.
=> chore: add new env vars into docs [sc-11927]

site/layouts/pricing/list.html
=> Updated /pricing page

site/content/docs/cli/constructs.md
=> chore: update from queryParams to queryParameters keyword

site/content/careers/_index.md, site/layouts/careers/list.html, src/scss/_careers.scss
Update values for current ones.
=> feat: update careers values [sc-14537]

site/content/docs/cli/command-line-reference.md
- add docs for CLI `destroy` command
- add docs for the `--config` flag in CLI commands.
Important: the new flags will be available in the next CLI `v0.4.8` release.
=> feat: add CLI destroy command docs [sc-0]

.github/workflows/checkly.yml, site/content/docs/cli/constructs.md
- fixes deploy command in GH actions
- fixes docs on JSON path example
=> ci: add id to GH actions + small docs update

site/content/docs/cli/command-line-reference.md
=> Slightly restructure CLI reference

site/content/docs/cli/constructs.md
=> fix: update constructs snippet

site/layouts/developers/list.html
Fix broken link `/developers`.
=> fix: link to blog on /developers

package-lock.json, package.json, site/content/docs/cli/command-line-reference.md, site/content/product/monitoring-as-code.mmark, site/layouts/partials/code-test-deploy-hero-section.html
- updates CLI commands ref
- removes "and" word
- updates test command to includes recording and github reporter
- Checkly CLI 0.4.10
Removes "and" between CTA buttons
=> feat: minimal update for CLI release 0.4.10

site/content/docs/integrations/prometheus.md
=> fix: fix typo in prometheus docs

.github/workflows/checkly.yml
- modify the GH Action flow to checkout the pull request branch and all the repository information before executing the tests.
=> chore: checkout PR branch before tests [sc-0]

site/content/docs/CICD/vercel.md
Fix link to Vercel password protection doc
=> Fix link to Vercel password protection doc

site/layouts/pricing/list.html
Move private locations from enterprise to team
=> feat: make private locations a team plan feature [sc-15059]

site/content/docs/private-locations/_index.md
Remove enterprise callout from private locations docs
=> feat: remove enterprise callout from private locations docs [sc-15059]

site/data/pricing/faq.yml
=> feat: update pricing faq [sc-00]

site/content/docs/browser-checks/playwright-test.md
=> feat(docs): add internal retry info to PWT features [sc-00]

site/content/docs/cli/command-line-reference.md, site/content/docs/cli/using-environment-variables.md
[Adding reference docs for ](https://github.com/checkly/checkly-cli/tree/main/packages/cli/src/commands/env)
=> add env command reference

.github/workflows/checkly.yml, __checks__/alertChannels.ts, __checks__/defaults.ts, __checks__/site.check-group.ts, checkly.config.ts, package-lock.json, package.json, site/content/docs/cli/constructs-reference.md, site/content/docs/cli/installation.md, site/content/docs/cli/project-structure.md
- move to checkly package
- update GH actions
- adds imported alert channels
- checkly
=> ci: updates to new CLI and adds imported alert channels

.gitignore, __checks__/404.spec.ts, __checks__/home.spec.ts, __checks__/pricing.spec.ts
- Updated checks for new marketing site locators, behaviour, etc.
- `404.spec.ts`
- `pricing.spec.ts`
- `home.spec.ts`
=> fix: 'checklyhq.com' related MaC checks for new marketing site '[sc-00]

site/content/_shared/cli-basics-for-cicd.md, site/content/_shared/main-cicd-cards.md, site/content/_shared/test-session-details.md, site/content/docs/testing/_index.md
Documented how one can configure test session details.
=> docs: add test session details

__checks__/site.check-group.ts
Just updating the check group of e2e tests.
=> chore: update check group for prod E2E

site/content/docs/CICD/github-actions.md
The instructions for GH action don't work. I moved the `checkly test` command into a single command.
=> fix: remove line break in command in github action docs

site/content/docs/alerting/alert-channels.md, site/content/docs/integrations/telegram.md
- Updated the `Integrations/Telegram` page to make the instructions more clear. Support couldn't figure out how to add Telegram, so we cleaned it up briefly
=> fix: refactor Telegram docs to clarify setup procedure [sc-00]

site/content/docs/private-locations/checkly-agent-configuration.md
Adding `LOG_LEVEL` to agent docs
=> agent: add LOG_LEVEL

.github/CODEOWNERS, .github/auto_assign.yml, site/content/docs/cli/constructs-reference.md, site/content/docs/dashboards/_index.md, site/content/docs/dashboards/custom-css.md, site/content/docs/dashboards/dashboard-customization.md, site/content/docs/dashboards/dashboard-look-feel.md, site/content/docs/dashboards/dashboard-url.md, site/content/docs/dashboards/incidents.md, site/content/docs/dashboards/legacy-dashboards.md, site/content/docs/maintenance-windows/_index.md
Add new CLI constructs docs.
Depends on https://github.com/checkly/checkly-cli/pull/763 to be released including the new resources.
=> docs: add new CLI resource constructs [sc-0]

site/content/docs/cli/constructs-reference.md
=> added shouldFail to ApiCheck constructs

site/content/docs/cli/npm-packages.md
Fix 1x broken link missing /docs/
Update link from GH issues to Featurebase
=> Update npm-packages.md again

site/content/docs/testing/_index.md, src/scss/_common.scss, src/scss/_markdown.scss
=> feat: adds video to testing [sc-00]

site/content/docs/testing/_index.md, src/scss/_common.scss
Ok, scratch that. For some reason the YT styles are scratched in the deploy pipeline. And I won't look into it right now. :D Just reverting here and going with your initial stuff. Sorry for the hoop.
=> fix: youtube shortcode

site/content/docs/alerting/phone-calls.md
=> add link to E.164 format page in phone-calls.md

site/content/docs/alerting/phone-calls.md, site/content/docs/alerting/sms-delivery.md, site/content/docs/terraform-provider/dashboards.md
=> update SMS & phone alert pages, TF dashboard

site/content/docs/cli/installation.md
=> Update installation.md with the latest cli versions

site/content/docs/cli/constructs-reference.md
=> Add Frequency import

site/content/docs/api-checks/_index.md, site/content/docs/cli/constructs-reference.md, site/content/docs/dashboards/authentication.md, site/content/docs/dashboards/custom-css.md, site/content/docs/dashboards/incidents.md
=> change from 'paid plans' to specific plan names

site/content/docs/alerting/alert-channels.md
Added phone calls to the alert channels overview.
=> fix: add phone calls to alert channel overview

.github/workflows/checkly.yml, site/content/docs/CICD/github-actions.md
As discussed, here's a fix for branch detection in GH Actions
=> fix: change GH actions CI/CD example to enable branch detection

site/content/docs/cli/command-line-reference.md
Fixed another typo in the `--tags` docs.
=> fix: fix another tiny typo in the `--tags` docs

vercel.json
Just adding some more redirects to clean up Google search console errors.
=> fix: clean up reported 404s in google search console

site/content/docs/browser-checks/playwright-test.md
Answered the if multiple test cases in a browser check count as `1` or `more` check runs last week. Added a quick note.
=> chore: add pricing note about PWT tests in a browser check

vercel.json
The `docs.` redirect needs to stay here.
=> fix: enable "docs.checklyhq" redirect again

site/content/docs/cli/constructs-reference.md, site/content/docs/terraform-provider/checks-groups.md
Add TF/CLI docs for Heartbeats
=> feat: add heartbeats to cli/tf [sc-17034]

site/content/docs/terraform-provider/checks-groups.md
=> feat: heartbeats tf minor copy change [sc-00]

site/content/docs/heartbeat-checks/_index.md
=> fix case consistency & typos

site/content/learn/headless/_index.md
"Slashifying" some more internal links to get rid of more Search Console warnings.
=> fix: cleaning up more some internal links to make search console happier

site/config.toml, site/layouts/index.html
Add /learn to top menu to improve crawlability
=> fix: improve learn section crawlability

README.md, algolia/config-docs.json, site/layouts/docs/baseof.html, site/layouts/docs/list.html, site/layouts/docs/single.html, site/layouts/guides/baseof.html, site/layouts/learn/baseof.html, site/layouts/partials/docs-menu-walk-list.html, site/layouts/partials/navbar-docs.html, src/scss/_common.scss, src/scss/_docs.scss, src/scss/_navbar.scss
adjusts docs structure as per https://docsearch.algolia.com/docs/legacy/required-configuration for better crawling
=> updates docs structure and crawler config for /docs

site/content/docs/monitoring/ip-info.md, site/content/docs/monitoring/responsible-use.md
What it says on the tin.
Note: do not deploy yet.
=> docs: adds ipv6 info

site/content/guides/openapi-swagger.md, site/content/guides/setup-scripts.md
Continue the journey to strengthen our internal link structure for SEO.
=> feat: add internal links to API monitoring article

algolia/config-docs.json, site/layouts/docs/list.html
- list pages were not indexed correctly due to missing class.
- any alert boxes were not indexed.
=> docs: adds correct classes for list pages and alerts

site/content/docs/cli/constructs-reference.md
[As discussed internally](https://checklyhq.slack.com/archives/C05B60JCTDL/p1694516469183439), it wasn't entirely clear what properties `HeartbeatCheck` inherits. This PR adjusts the `Check` construct docs to make it clearer.
=> chore: adjust the "Check" construct docs

site/content/docs/cli/constructs-reference.md
@shiini2 Just implementing your suggestion. 🎉
=> chore: condense Check type table

site/content/docs/cli/npm-packages.md, site/content/docs/cli/using-environment-variables.md
- removes false notice of API checks not using dependencies
- adds better inline examples of `env` command
=> docs: small updates and fixes

__checks__/site.check-group.ts, checkly.config.ts
Update check to add `retryStrategy` on groups and checks.
=> feat(retries): add `retryStrategy` to config + group [sc-00]

site/content/docs/integrations/prometheus-v2.md
We're currently making updates to the Prometheus V2 endpoint. This PR updates the documentation accordingly.
The big changes are:
* There's now a rate limit
* There's no longer a `region`/`location` label.
=> docs: update Prometheus V2 docs

site/content/docs/heartbeat-checks/_index.md
A little delayed, but as part of the heartbeats release I'm adding a YT explainer video to the heartbeats docs.
https://www.youtube.com/watch?v=7I_NfCjYCmo
=> feat: add heartbeats explainer video

site/content/docs/browser-checks/_index.md
clarifies support for Chrome in 2023.02 and later
=> Clarify Chrome support for browser checks

site/content/docs/accounts-and-users/creating-api-key.md
- Adds section on service API keys
- Explains how they differ from User API keys.
=> docs: adds service API keys docs [sc-00]

site/content/docs/cli/constructs-reference.md, site/content/docs/heartbeat-checks/_index.md, site/content/docs/retries-and-alerting/ssl-expiration.md, site/content/guides/monitoring-as-code-cli.md
=> fix: fix broken links

site/layouts/learn/_markup/render-heading.html, src/scss/_learn.scss
Add hash links in learn titles
=> feat: add hash links in learn [sc-18021]

site/content/docs/multistep-checks/_index.md
=> add beta limitations to multistep docs

site/content/docs/monitoring/allowlisting.md
Naming was changed in https://github.com/checkly/docs.checklyhq.com/pull/937 which breaks any previous indexing in our internal search and on search engines (users are hitting a 404).
@drakirnosslin please remember to add an alias (redirects) if you change routes.
=> feat: add redirect to allowlist [sc-00]

site/content/docs/private-locations/scaling-and-redundancy.md
Update the agent timeout from 140s to 300s
=> Update the agent timeout

site/layouts/partials/scripts.html
=> feat: add koala script on body [sc-18362]

site/layouts/partials/head.html
=> fix: load intercom after user scroll [sc-00]

site/content/docs/CICD/vercel.md, site/content/docs/integrations/opsgenie.md, site/content/guides/end-to-end-monitoring.md, site/content/learn/headless/basics-puppeteer-intro.md, site/layouts/partials/head.html
=> add meta titles and update meta descriptions

site/content/docs/alerting-and-retries/alert-settings.md
In English, the name of the city in question is spelt "Tokyo". 🙂 
Anyway, thanks for the docs! 👍
=> [minor] Update alert-settings.md to fix name of physical location

site/content/docs/monitoring/_index.md, site/content/docs/monitoring/check-results.md, site/content/docs/monitoring/global-locations.md
=> chore: parallel scheduling beta docs [sc-18383]

site/content/docs/cli/constructs-reference.md, site/content/docs/terraform-provider/checks-groups.md
Adding the new prop to TF & CLI docs
=> feat: add runParallel prop to CLI & TF docs [sc-00]

site/content/docs/monitoring/allowlisting.md, site/content/docs/monitoring/ip-info.md
=> 🗿 add static IPs

site/content/docs/monitoring/allowlisting.md
=> 🐝 add static IPv6 info

site/content/docs/monitoring/check-pricing.md
=> add pricing breakdown page

site/content/docs/monitoring/check-pricing.md
=> add base price for multistep

site/content/docs/CICD/vercel.md, site/content/docs/api-checks/setup-script-examples.md
Changed links pointing to https://www.checklyhq.com/docs/cicd/vercel-authentication/ to working URL
=> fix: 404 on /docs [sc-18855]

site/content/docs/alerting-and-retries/alert-settings.md
The callout banner info being after the image makes it difficult to see. And this is already a concept users often misunderstand, so we need to be very clear.
=> docs: update alert-settings

site/content/docs/multistep-checks/upload-downloads-filesystem.md, site/content/docs/multistep-checks/websockets.md
=> added new websockets page

site/content/docs/cli/constructs-reference.md
Add documentation for alert escalation policies
=> feat: add alert escalation policy

site/content/docs/monitoring/global-locations.md
=> feat: remove parallel disclaimer [sc-00]

site/content/docs/alerting-and-retries/sms-delivery.md
=> update SMS alert number

site/content/docs/terraform-provider/alerting.md
=> feat: TF docs alerting parallel [sc-00]

site/content/learn/headless/generating-pdfs.md
Replace old URL to avoid unnecessary redirects
=> fix: change redirect to https://www.checklyhq.com/ [sc-19299]

site/content/docs/cli/constructs-reference.md
Adding docs for new alert settings options in the CLI
=> feat: add cli parallel threshold to docs [sc-00]

site/content/docs/monitoring/allowlisting.md, site/content/docs/multistep-checks/_index.md
Adds clarifications around the new user-agent `Checkly/1.0` used for requests and how to set a custom one.
=> refactor(multistep): clarify user-agent default [sc-19306]

site/layouts/partials/head.html
**We can't test this before merging due to CookieYes limitations**
Added the CookieYes script to include the cookie banner on the repository.
=> feat: add cookie banner on docs [sc-19436]

site/content/docs/cli/project-structure.md, site/content/docs/cli/using-check-test-match.md
Adding docs for cli ms glob support
=> feat: multistep glob support cli [sc-00]

site/content/docs/alerting-and-retries/sms-delivery.md
=> update supported countries & regions

site/content/docs/browser-checks/timeouts.md
Goes along with the update in templates to add a test timeout: https://github.com/checkly/checkly-webapp/pull/6781
https://checklyhq.slack.com/archives/C024ZAJ938S/p1712849575159769?thread_ts=1711616952.915219&cid=C024ZAJ938S
=> feat: update test timeout [sc-19908]

site/content/docs/multistep-checks/_index.md
=> add timeout info to ms checks

site/content/docs/browser-checks/playwright-test.md
For more info, see https://app.shortcut.com/checkly/story/18115/baseurl-isn-t-supported-on-checkly
=> docs: rectify baseurl support

site/content/docs/api-checks/setup-script-examples.md
Updated old auth0 setup scripts for client-credentials and password grant
=> update auth0 setup-scripts

site/content/docs/monitoring/check-results.md
=> Update check duration description

site/content/docs/integrations/pagerduty.md, site/content/docs/integrations/telegram.md, site/content/learn/headless/_index.md, site/content/learn/headless/basics-navigation.md, site/content/learn/headless/basics-playwright-intro.md, site/content/learn/headless/basics-selectors.md
- turned up a number of linting errors, none of which were in the stuff I was changing
This update should only affect metadata on the updated pages with no visual changes. Updates requested by SEO agency
is this right? it doesn't look right `<meta property="“og:title”" content="Working with selectors | Checkly">`
I noticed while doing these updates that the template file for the <head> component appears to have an [error in its meta title tag](https://github.com/checkly/docs.checklyhq.com/blob/2f9dac7e6afa349d68a89af5c171cecc684eef4f/site/layouts/partials/head.html#L13) (smart quotes) and this is causing an extra set of quotes to render in the page. Not being an experienced front-end developer I didn't know if this was possibly intentional, so didn't edit. If you, gentle reviewer, know …
=> update titles & descriptions

package-lock.json, site/content/docs/cli/using-environment-variables.md
Draft PR for previewing purposes
=> add example for apiCheck remote env var

site/content/docs/runtimes/_index.md
=> Update package request process

site/content/docs/monitoring/allowlisting.md
small tweak to leverage the new copy to clipboard feature
=> docs: make API calls easier to copy & paste [sc-00]

site/content/docs/alerting-and-retries/ssl-expiration.md
This PR documents a limitation with SSL checks and handlebars syntax. We also just switched the SSL checks to run hourly rather than daily.
=> feat: explain Handlebars limitations for SSL checks

site/content/docs/accounts-and-users/multi-factor-authentication.md
=> Fix pricing specifics

site/content/docs/traces-open-telemetry/_index.md
=> Set Alias from open-telemetry to traces-open-telemetry

site/content/docs/alerting-and-retries/phone-calls.md, site/content/docs/alerting-and-retries/sms-delivery.md
=> Updated supported countries for SMS and Phone calls

site/content/docs/alerting-and-retries/retries.md
* Organize and re-word retries page
* Include CLI Test session retries
* The whole retries page has been edited to make space for Test session retries 💪🏼
=> Update retries and include test session CLI retries

site/content/docs/cli/command-line-reference.md
Adds proper docs on using the new CLI JSON reporter.
=> docs: adds json reporter [sc-00]

site/content/docs/integrations/msteams.md
=> Update incoming webhook to workflow in one more place

site/content/docs/cli/installation.md
Update our CLI CDN links to latest Checkly CLI version.
=> chore: update our CLI assets

site/content/docs/_index.md, site/content/docs/alerting-and-retries/alert-channels.md, site/content/docs/browser-checks/_index.md, site/content/docs/integrations/opsgenie.md, site/content/docs/integrations/telegram.md, site/content/docs/monitoring/global-locations.md, site/content/docs/private-locations/_index.md, site/content/learn/headless/basics-scraping.md
=> fix: redirects and links on docs [sc-21586]

site/content/docs/alerting-and-retries/phone-calls.md
[shortcut 21346](https://app.shortcut.com/checkly/story/21346/add-belgium-malta-to-supported-alerting-phone-calls)
PR adds two new countries to the supported countries for phone call alerting.
~* [ ] Code is linted (`npm run lint`)~
=> feat: add Belgium and Malta to the supported countries for phone call alerting

site/content/docs/cli/using-environment-variables.md, site/content/docs/monitoring/storing-secrets.md
=> clarify secrets usage in CLI docs and monitoring overview.

vercel.json
* [ X ] Learn
Added the redirects we need. 
All set
=> Dg fix learn redirects 2

site/content/_shared/variables-and-secrets.md, site/content/docs/cli/command-line-reference.md, site/content/docs/groups/variables.md
=> add trace clarification and version details.

site/content/docs/cli/constructs-reference.md
=> feat: make env var strings booleans [sc-00]

site/content/docs/alerting-and-retries/alert-channels.md
=> add cli to alert admonition

site/content/learn/playwright/playwright-vs-cypress.md, site/content/learn/playwright/playwright-vs-others.md
=> Pwt vcypress

site/config.toml, site/content/docs/integrations/prometheus-v2.md, site/content/guides/empowering-developers-with-checkly.md, site/content/guides/end-to-end-monitoring.md, site/content/guides/monitoring-an-openapi-spec.md, site/content/guides/monitoring-as-code.md, site/content/guides/monitoring-ecommerce-apps-using-playwright.md, site/content/guides/monitoring-ecommerce-apps-using-terraform.md, site/content/guides/monitoring-the-stripe-api.md, site/content/guides/moving-from-puppeteer-to-playwright.md, site/content/guides/setup-scripts-for-apis.md, site/content/guides/the-programmable-monitoring-platform.md, site/layouts/guides/list.html, site/layouts/guides/single.html, src/scss/_guides.scss
* [ X ] Guides
Redesigned the Guides section and added tags
=> Simple redesign of guide section

site/content/docs/alerting-and-retries/webhooks.md
Alert type was incorrect. I adjusted it and linked the full list of available types.
Before
After
=> feat: adjust alert states [sc-00]

site/content/learn/playwright/what-is-playwright.md, vercel.json
=> Changed getting-started playwright to what-is-playwright and redirected

site/layouts/docs/single.html
* [ X ] Docs
* [ X ] Learn
Changed out the footer links to show Display links and not the Title link.
This is much more human friendly and readable.
=> fixed footer links to show display title

site/layouts/guides/list.html, src/scss/_guides.scss, src/scss/_learn.scss
- Cards are clickable now. No need to snipe the links.
- Small CSS fixes to align card items easier and neater.
=> style: css and dom fixes for better mobile and layout [sc-00]

site/content/guides/monitoring-as-code.md, site/content/learn/playwright/clicking-typing-hovering.md, site/content/learn/playwright/how-to-set-up-locally.md, site/content/learn/playwright/navigation.md, site/content/learn/playwright/what-is-playwright.md, vercel.json
=> fixed some redirects and meta titles

site/content/docs/traces-open-telemetry/importing-traces/troubleshooting-missing-spans.md
=> fix: broken urls on traces [sc-00]

site/content/docs/browser-checks/playwright-test.md
See https://github.com/checkly/checkly-cli/releases/tag/4.12.0 for reference
=> Updated docs with support for proxy in playwright config

site/content/learn/playwright/_index.md, site/content/learn/playwright/test-fixtures.md, site/layouts/shortcodes/youtube-gallery.html
This PR extends the fixture best practices article with content from a recently released video.
Additionally, I reworked the youtube playlist embed to render different lists. We now have the "general" list high in the hierarchy and a focused "Playwright fixtures" list in the fixtures article.
| PWT Playlist | Fixture Playlist |
|--------|--------|
| <img width="896" alt="grafik" src="https://github.com/user-attachments/assets/0a367c4a-1ef0-4127-b585-db3b597fc2b0"> | <img width="900" alt="grafik" src="https://github.com/user-attachments/assets/ad03766d-a264-4f78-9ac5-5d713adb06a4"> |
=> Update fixtures article

vercel.json
rewrite specific paths instead of all
=> fix: redirect try 2

site/content/docs/monitoring/check-pricing.md, site/content/docs/tcp-checks/_index.md
=> Added pricing reference to TCP docs

site/content/learn/playwright/authentication.md
=> fix links that were going to our internal notion (!!)

site/content/docs/tcp-checks/_index.md
=> Updated early access announcement

site/content/docs/tcp-checks/_index.md
=> Add TCP check examples

site/content/docs/monitoring/_index.md, site/content/docs/monitoring/check-pricing.md, site/content/docs/monitoring/global-locations.md, site/content/docs/tcp-checks/_index.md
=> Updated TCP docs

site/content/docs/CICD/github-actions.md, site/content/docs/CICD/gitlabci.md, site/content/docs/CICD/jenkins.md, site/content/docs/cli/command-line-reference.md, src/js/index.js
Small fixes I bumped into helping a user.
=> docs: updates some docs based on customer discussion.

__checks__/defaults.ts
=> fix: change baseUrl for prod url [sc-00]

site/config.toml, site/content/docs/tcp-checks/_index.md, site/content/docs/traces-open-telemetry/_index.md, site/content/docs/traces-open-telemetry/exporting-traces/_index.md, site/content/docs/traces-open-telemetry/exporting-traces/dash0.md, site/content/docs/traces-open-telemetry/exporting-traces/grafana-tempo.md, site/content/docs/traces-open-telemetry/exporting-traces/honeycomb.md, site/content/docs/traces-open-telemetry/exporting-traces/newrelic.md, site/content/docs/traces-open-telemetry/how-it-works.md, site/content/docs/traces-open-telemetry/importing-traces/_index.md, site/content/docs/traces-open-telemetry/importing-traces/http-vs-grpc-protocols.md, site/content/docs/traces-open-telemetry/importing-traces/sending-traces-otel-collector.md, site/content/docs/traces-open-telemetry/importing-traces/troubleshooting-missing-spans.md, site/content/docs/traces-open-telemetry/instrumenting-code/_index.md, site/content/docs/traces-open-telemetry/instrumenting-code/django.md, site/content/docs/traces-open-telemetry/instrumenting-code/dot-net.md, site/content/docs/traces-open-telemetry/instrumenting-code/express.md, site/content/docs/traces-open-telemetry/instrumenting-code/flask.md, site/content/docs/traces-open-telemetry/instrumenting-code/go.md, site/content/docs/traces-open-telemetry/instrumenting-code/java.md, site/content/docs/traces-open-telemetry/instrumenting-code/laravel.md, site/content/docs/traces-open-telemetry/instrumenting-code/nextjs.md, site/content/docs/traces-open-telemetry/instrumenting-code/nodejs.md, site/content/docs/traces-open-telemetry/instrumenting-code/ruby-on-rails.md
removes beta tags from traces.
=> docs: remove beta / early access tags.

site/content/docs/integrations/pulumi.md
PR adds an example of the tcp check into the pulumi integration doc.
=> feat: mention tcp in pulumi integration

site/content/docs/cli/constructs-reference.md
- adds docs on incident.io construct for the CLI to be released at CLI 5.x.x
=> feat: adds docs on CLI incident.io, Teams and Telegram channel.

checkly.config.ts, site/content/docs/cli/_index.md, site/content/docs/cli/installation.md, site/content/guides/developer-fixtures.md, site/content/guides/end-to-end-monitoring.md, site/content/guides/getting-started-with-monitoring-as-code.md, src/js/cliCopyButton.js
Adds the `@latest` to the `npm create checkly` command.
=> docs: update command.

site/content/docs/private-locations/checkly-agent-configuration.md
=> fix agent version and runtime table

site/content/docs/alerting-and-retries/sms-delivery.md
PR for the webapp is here https://github.com/checkly/checkly-webapp/pull/7966
=> feat: remove saudia arabia from allowed countries for SMS [sc-00]

site/content/docs/browser-checks/playwright-test.md
* ATM launchOptions are not supported https://checklyhq.slack.com/archives/C03CQMZE3L1/p1742551092859379
=> LaunchOptions are not supported ATM

site/content/learn/monitoring/defining-mttr.md, site/content/learn/monitoring/mttr-challenges.md
=> fix: seo improvements and link fixes [sc-00]

site/content/docs/status-pages/_index.md, site/content/docs/status-pages/incidents.md
=> add small fixes, add note about UTC times.

site/config.toml, site/content/docs/playwright-checks/_index.md, site/content/docs/playwright-checks/reference.md
It's WIP, but you can start early on what's there so that it's incorporated early.
=> playwright checks in alpha!

site/content/docs/playwright-checks/_index.md
=> clarify where to run things from and add proper numbering

site/content/docs/accounts-and-users/multi-factor-authentication.md
The actual functionality and marketing page have already been updated.
=> MFA now available for all plans

site/content/docs/playwright-checks/_index.md, site/content/docs/playwright-checks/reference.md
Add a link to get the feature flag preventing users getting 403
=> fix: add private alpha warning [sc-00]

site/content/docs/CICD/github.md, site/content/docs/CICD/vercel.md, site/content/docs/accounts-and-users/_index.md, site/content/docs/accounts-and-users/changing-your-email-password.md, site/content/docs/alerting-and-retries/ssl-expiration.md, site/content/docs/api-checks/setup-teardown-scripts.md, site/content/docs/cli/npm-packages.md, site/content/docs/integrations/telegram.md, site/content/docs/maintenance-windows/_index.md, site/content/docs/terraform-provider/troubleshooting.md
=> Many small improvements, including minor content additions and typo fixes

site/config.toml, site/content/_shared/playwright-native-alpha.md, site/content/docs/playwright-checks/_index.md, site/content/docs/playwright-checks/reference.md
Overall it includes: 
* Change name to Playwright Check Suites
* Make steps linkable in getting started
* Add better example snippets
* Update reference with headers and groupName
* use shared alpha blurb
=> Change name to Playwright Check Suites

site/content/docs/playwright-checks/_index.md
=> fix: remove alpha flag step [sc-00]

site/content/docs/api-checks/_index.md, site/content/docs/monitoring/_index.md
See https://checklyhq.slack.com/archives/C08F2AA6DMX/p1745400622600369 for context
=> Added note on 1 sec freq. for API checks

site/content/docs/api-checks/request-settings.md, site/content/docs/tcp-checks/_index.md
https://www.notion.so/checkly/Manage-should-fail-via-assertion-1f1ec050b06e802c924bdc1d379b973d?pvs=4#1f2ec050b06e804f84feebcac7d9b02e
=> Adjusted should fail docs

site/layouts/_default/index.txt
* [x ] Docs
* [x ] Code is linted (`npm run lint`)
More test have shown that the following notes helped the llm to guide the user significantly better
=> Feat-lmstxt

site/static/docs/ai/checkly.rules.md
=> feat: add clearer instructions on install.

gulpfile.mjs, site/config.toml, src/js/index.js, src/scss/_syntax.scss
=> fix: small rendering bugs.

site/content/docs/playwright-checks/_index.md, site/content/docs/playwright-checks/add-to-group.md
Something that slipped through before :)
=> fix h2 and h3 headings with consistency

site/content/docs/cli/constructs-reference.md, site/content/docs/url-monitors/_index.md
Add "should fail" reference for URL monitors
=> added should fail reference for url monitors

site/content/_shared/playwright-native-notice.md, site/content/docs/ai/use-checkly-with-ai-ide.md
=> Removed redundant copy
